export const REGISTER_USER = 'REGISTER_USER';
export const REGISTERING_USER = 'REGISTERING_USER';
export const REGISTERED_USER = 'REGISTERED_USER';

export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const CHANNELS_LOADED = 'CHANNELS_LOADED';

export const CATALOGUE_LOADING = 'CATALOGUE_LOADING';
export const CATALOGUE_LOADED = 'CATALOGUE_LOADED';

export const FETCHING_CHANNEL = 'FETCHING_CHANNEL';
export const FETCHED_CHANNEL = 'FETCHED_CHANNEL';

export const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
export const FETCHED_CATEGORIES = 'FETCHED_CATEGORIES';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';

export const CATEGORY_ITEMS_LOADING = 'CATEGORY_ITEMS_LOADING';
export const CATEGORY_ITEMS_LOADED = 'CATEGORY_ITEMS_LOADED';

export const CATALOGUE_URI_LINK_LOADED = 'CATALOGUE_URI_LINK_LOADED';
export const CATALOGUE_URI_LINK_OBJECT_CREATED = 'CATALOGUE_URI_LINK_OBJECT_CREATED';




export const CHANNEL_IMAGE_URI_LOADED = 'CHANNEL_IMAGE_URI_LOADED';

export const CHANNEL_GUIDE_LOADED = 'CHANNEL_GUIDE_LOADED';

export const CHANNEL_RSTP_LINK_LOADED = 'CHANNEL_RSTP_LINK_LOADED';
export const CHANNEL_RSTP_LINK_OBJECT_CREATED = 'CHANNEL_RSTP_LINK_OBJECT_CREATED';

export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';

export const STREAM_LOADED_TYPE = 'STREAM_LOADED_TYPE';
