export const SESSION_RESTORING = 'SESSION_RESTORING';
export const SESSION_LOADING = 'SESSION_LOADING';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';


export const API_SESSION_RESTORING = 'API_SESSION_RESTORING';
export const API_SESSION_LOADING = 'API_SESSION_LOADING';
export const API_SESSION_SUCCESS = 'API_SESSION_SUCCESS';
export const API_SESSION_ERROR = 'API_SESSION_ERROR';
export const API_SESSION_REGISTER = 'API_SESSION_REGISTER';


export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';

export const GET_USER = 'GET_USER';

export const GET_WIFI_OPTION = 'GET_WIFI_OPTION';